; Source: Bradley & Manna, The Calculus of Computation, Example 9.13 (adapted)
(set-logic QF_UF)
(set-info :source "Bradley & Manna, The Calculus of Computation, Example 9.13 (adapted)")
(set-info :status unsat)
(declare-sort U 0)
(declare-fun a () U)
(declare-fun b () U)
(declare-fun i () U)
(declare-fun v () U)
(declare-fun store (U U U) U)
(declare-fun select (U U) U)

(assert (= a (store b i v)))
(assert (not (= (select a i) v)))
(check-sat)
(exit)
